name: HACS Validation

on:
  pull_request:
    branches:
      - my-main
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@1.0.0"
